foreground                      #e3e2e6
background                      #101114
selection_foreground            #e0e2ec
selection_background            #273141

#: Cursor colors

cursor                          #a8c8ff

#: URL underline color when hovering with mouse

url_color                       #7cacfa

#: Tab bar colors

active_tab_foreground           #ffffff
active_tab_background           #265ea7
inactive_tab_foreground         #8e9099
inactive_tab_background         #181c22

#: The basic 16 colors

#: black
color0                          #1a1c1e
color8                          #5b5e66

#: red
color1                          #ba1a1a
color9                          #ff897d

#: green
color2                          #4478c1
color10                         #6091dd

#: yellow
color3                          #dcbce1
color11                         #f9d8fe

#: blue
color4                          #265ea7
color12                         #7cacfa

#: magenta
color5                          #6f5675
color13                         #bfa1c5

#: cyan
color6                          #555f71
color14                         #a2abc0

#: white
color7                          #c7c6ca
color15                         #ffffff
