# sudo pacman -S zsh starship zoxide zsh-syntax-highlighting

PROMPT='%F{242}%2~%f '

if [[ -o interactive ]]; then

    HISTFILE=~/.zsh_history
    HISTSIZE=10000
    SAVEHIST=10000

    setopt append_history
    setopt share_history
    setopt inc_append_history
    setopt hist_ignore_dups
    setopt hist_ignore_all_dups
    setopt hist_ignore_space
    setopt hist_reduce_blanks
  
    command -v zoxide   &>/dev/null && eval "$(zoxide init zsh --cmd cd)"

    alias i="sudo pacman -S --needed"
    alias r="sudo pacman -Rns"
    alias aur="yay -S"
    alias update="yay -Syu"
    alias v="nvim"
    alias x="pwd"
    alias clear="printf '\033[2J\033[3J\033[1;1H'"

    bindkey '^[[1;5D' backward-word            
    bindkey '^[[1;5C' forward-word            
    bindkey '^[[1;3D' backward-word           
    bindkey '^[[1;3C' forward-word            
    bindkey '^[[H'    beginning-of-line       
    bindkey '^[[F'    end-of-line             
    bindkey '^[[3~'   delete-char             
    bindkey '^?'      backward-delete-char    

    [[ -f /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh ]] && \
        source /usr/share/zsh/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh

    fi
