font_family  JetBrainsMono Nerd Font
font_size    11.0

window_margin_width 15

confirm_os_window_close 0

shell zsh

map ctrl+c copy_or_interrupt
map ctrl+v paste_from_clipboard
map ctrl+shift+c send_text all \x03

map alt+enter new_tab
map alt+q     close_tab

map alt+left  previous_tab
map alt+right next_tab

draw_minimal_borders no
dynamic_background_opacity yes

clipboard_control write-clipboard write-primary read-clipboard-ask read-primary-ask

url_style        curly
open_url_with    default
detect_urls      yes
url_regex        (ipfs:|ipns:|magnet:|mailto:|gemini:|gopher:|https:|http:|news:|file:|git:|ssh:|ftp:)[^-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+

disable_ligatures never
adjust_line_height 2

enable_audio_bell no

cursor_shape block
cursor_trail 2
shell_integration no-cursor
cursor_blink_interval 0

tab_bar_style        powerline
tab_powerline_style  slanted
tab_bar_edge         top

include themes/blue.conf
